from spaceone.inventory.connector.virtual_machine import VirtualMachineConnector
from spaceone.inventory.connector.virtual_machine_scale_set import VmScaleSetConnector
from spaceone.inventory.connector.subscription import SubscriptionConnector
from spaceone.inventory.connector.sql import SqlConnector
from spaceone.inventory.connector.monitor import MonitorConnector
from spaceone.inventory.libs.connector import AzureConnector
