from spaceone.inventory.libs.manager import AzureManager
from spaceone.inventory.manager.virtual_machine_manager import VirtualMachineManager
from spaceone.inventory.manager.virtual_machine_scale_set_manager import VmScaleSetManager
from spaceone.inventory.manager.subscription_manager import SubscriptionManager
from spaceone.inventory.manager.sql_server_manager import SqlServerManager


